#To use:
#    $ conda install -n base -c conda-forge mamba
#    $ conda create -n mbo-caiman -f /path/to/repo/environment.yml
#    $ conda activate mbo-caiman
name: mbo-caiman
channels:
- conda-forge
- defaults
dependencies:
# Core
- python <=3.9
- pip
- ipykernel
- ipython
- ipyparallel
- cython
- psutil

# Scientific libs
- numpy <2.0.0
- scikit-image >=0.19.0
- scikit-learn >=1.2
- scipy >= 1.10.1
- caiman
- peakutils # 1D peak detection
- jupyter

# Visuals
- jupyter_bokeh
- holoviews >=1.16.2
- matplotlib
- bokeh >=3.1.1
- moviepy
- pyqtgraph
- panel >=1.0.2
- tk # simple gui tkinter

#io
- opencv
- h5py
- pynwb
- zarr
- tifffile
- pims # interface for tiff readers
- av # ffmpeg binaries
- tqdm

# Non-conda libs
- pip:
  - -e git+https://github.com/ru-rbo/scanreader.git#egg=argh
  - scanreader
