#To use:
#    $ conda install -n base -c conda-forge mamba
#    $ conda env create -n mbo-py -f /path/to/repo/environment.yml
#    $ conda activate mbo-caiman
channels:
- conda-forge
dependencies:
- python
- mesmerize-core
- napari
- pyqt
- pip
- napari
- fastplotlib=0.2.0
- simplejpeg

