channels:
- conda-forge
- default
dependencies:
- python <=3.9
- av
- bokeh >=3.1.1
- cython
- suite2p
- h5py
- holoviews >=1.16.2
- ipykernel
- ipython
- ipyparallel
- jupyter
- jupyter_bokeh
- matplotlib
- moviepy
- mypy
- nose
- numpy <2.0.0
- opencv
- panel >=1.0.2
- peakutils
- pims
- psutil
- pynwb
- pyqtgraph
- scikit-image >=0.19.0
- scikit-learn >=1.2
- scipy >= 1.10.1
- tensorflow >=2.4.0
- tifffile
- tk
- tqdm
- yapf
- zarr

#TODO: move to environment-dev.yml
- black
- icecream
- numpydoc
- sphinx
- coverage
