#To use:
#    $ conda install -n base -c conda-forge mamba
#    $ conda env create -n mbo-py -f /path/to/repo/environment.yml
#    $ conda activate mbo-py
name: mbo-caiman  # changing this will mean changing `conda activate <my-package-name>
channels:
- conda-forge
# - defaults
dependencies:
- pip
- pip:
  - git+https://github.com/MillerBrainObservatory/scanreader.git#egg=scanreader
- caiman
# - python <=3.9
# - av
# - cython
# - h5py
# - ipykernel
# - ipython
# - ipyparallel
# - jupyter
# - jupyter_bokeh
# - matplotlib
# - moviepy
# - nose
# - numpy <2.0.0
# - opencv
# - panel >=1.0.2
# - peakutils
# - pims
# - psutil
# - pynwb
# - pyqtgraph
# - scikit-image >=0.19.0
# - scikit-learn >=1.2
# - scipy >= 1.10.1
# - tensorflow >=2.4.0
# - tifffile
# - tk
# - tqdm
# - yapf
# - zarr
# - nbsphinx
