name: Install with Miniforge

on:
  pull_request:
    branches:
      - master
      - dev
  push:
    branches: [ master ]

jobs:
  install-with-miniforge:
    name: Install with (${{ matrix.os }}, Miniforge)
    runs-on: ${{ matrix.os }}-latest
    strategy:
      matrix:
        os: ["ubuntu", "windows"]
    steps:
      - uses: actions/checkout@v4
      - uses: conda-incubator/setup-miniconda@v3
        with:
          environment-file: etc/example-environment.yml
          miniforge-version: latest

      - name: Create and activate LBM environment
        shell: bash
        run: |
          conda create -n lbm -c conda-forge mesmerize-core -y
          echo "conda activate lbm" >> $GITHUB_ENV

      # - name: Install CaImAn and other dependencies
      #   shell: bash
      #   env:
      #     PATH: ${{ env.PATH }}:/opt/hostedtoolcache/miniconda3/bin
      #   run: |
      #     source $CONDA/bin/activate lbm
      #     caimanmanager install
      #     pip install lbm_caiman_python
      #     pip install git+https://github.com/atlab/scanreader.git
      #
