name: Install with Miniforge

on:
  pull_request:
    branches:
      - master
      - dev
  push:
    branches: [ master ]

jobs:
  install-with-miniforge:
    name: Install with (${{ matrix.os }}, Miniforge)
    runs-on: ${{ matrix.os }}-latest
    strategy:
      matrix:
        os: ["ubuntu", "windows"]
    steps:
      - name: Check out the repository
        uses: actions/checkout@v4

      - name: Set up Miniforge
        uses: conda-incubator/setup-miniconda@v3
        with:
          miniforge-version: latest

      - name: Create and activate LBM environment
        shell: bash
        env:
          CONDA: ${{ env.CONDA }}
        run: |
          source $CONDA/etc/profile.d/conda.sh
          conda create -n lbm -c conda-forge mesmerize-core -y
          echo "conda activate lbm" >> $GITHUB_ENV
          echo "Conda activated successfully!"

      # - name: Install CaImAn and other dependencies
      #   shell: bash
      #   env:
      #     CONDA: ${{ env.CONDA }}
      #   run: |
      #     source $CONDA/etc/profile.d/conda.sh
      #     conda activate lbm
      #     caimanmanager install
      #     pip install lbm_caiman_python
      #     pip install git+https://github.com/atlab/scanreader.git
      #
