name: Install with Miniforge (Linux)

on:
  pull_request:
    branches:
      - master
      - dev
  push:
    branches: [ master ]

jobs:
  install-with-miniforge:
    name: Install with (${{ matrix.os }}, Miniforge)
    runs-on: ${{ matrix.os }}-latest
    strategy:
      matrix:
        os: ["ubuntu"]
    steps:
      - name: Check out the repository
        uses: actions/checkout@v4

      - name: Set up Miniforge
        uses: conda-incubator/setup-miniconda@v3
        with:
          miniforge-version: latest

      - name: Create LBM environment
        shell: bash
        env:
          CONDA: ${{ env.CONDA }}
        run: |
          source $CONDA/etc/profile.d/conda.sh
          conda create -n lbm -c conda-forge python=3.10 caiman -y

      - name: Activate LBM environment and install dependencies
        shell: bash
        env:
          CONDA: ${{ env.CONDA }}
        run: |
          source $CONDA/etc/profile.d/conda.sh
          conda activate lbm
          git clone https://github.com/flatironinstitute/CaImAn.git
          cd CaImAn
          pip install --upgrade pip
          pip install -e .
          caimanmanager install
          cd ..

          # Install Python dependencies
          pip install git+https://github.com/atlab/scanreader.git
          git clone https://github.com/MillerBrainObservatory/LBM-CaImAn-Python.git
          cd LBM-CaImAn-Python
          pip install -e .
          cd ..